/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 badMan.glb --transform 
Files: badMan.glb [23.7MB] > E:\dreamStream\vite-project\public\models\robot\badMan-transformed.glb [486.86KB] (98%)
Author: GreenG (https://sketchfab.com/AngelNebesniy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/robot-from-the-series-love-death-and-robots-3c2c43c8737341e5816c61634782373a
Title: Robot from the series "Love death and robots"
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('./models/robot/badMan-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.01}>
          <group name="Empty" position={[2.458, 0, -102.215]} rotation={[0, 0, Math.PI / 2]} />
          <group name="Kosti" position={[13.777, 460.07, -5.148]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
            <group name="Object_7">
              <primitive object={nodes._rootJoint} />
              <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.Material} skeleton={nodes.Object_10.skeleton} />
            </group>
          </group>
          <group name="Empty001" position={[13.138, 0.369, 88.479]} rotation={[0, 0, -Math.PI / 2]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/robot/badMan-transformed.glb')
